# Numpy, Mátrixok
Ez előtt a téma előtt érdemes a szintaktikában eljutni a Ciklusok tananyagig
## Mátrixok
A mátrixok alapvető eszközök sok területen.
-képfeldolgozás
-grafika
-mesterséges intelligencia
-adattárolás
-adatbányászás
(Fun Fact: Pont ezért van az, hogy a grafikai számításokat végző videókártya ennyire kell az adatbányászathoz és a mesterséges intelligencia számításokhoz)

In [23]:
# Egy mátrix az listák listája
# Még hozzá szabályos, tehát minden sorban ugyanannyi elem kell, hogy legyen

a = [[1,0,0,0,0],
     [0,1,0,0,0],
     [0,0,1,0,0],
     [0,0,0,1,0]]
for lm in a:
    print(lm)

[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]


In [24]:
# Amikor egy mátrix dimenzióiról beszélünk, akkor azt mondjuk meg, hány lista van egymásba ágyazva
# Az előző példában 2D listáról beszéltünk, mert van szélessége, magassága
# A 3D listában 3 szintre megyünk a listában

a = [[[1,1,1], [1,0,1], [1,1,1]],
     [[1,0,1], [0,0,0], [1,0,1]],
     [[1,1,1], [1,0,1], [1,1,1]]]
for lm in a:
    print(lm)

[[1, 1, 1], [1, 0, 1], [1, 1, 1]]
[[1, 0, 1], [0, 0, 0], [1, 0, 1]]
[[1, 1, 1], [1, 0, 1], [1, 1, 1]]


___
# Numpy
## Létrehozás

In [25]:
import numpy as np
# A numpy fő célja a nagy mennyiségű adat kezelése
# Ez gyakorlatilag egy olyan tömb, amin kényelmesen lehet műveleteket végezni
a_ = [[1,0,0,0,0],
     [0,1,0,0,0],
     [0,0,1,0,0],
     [0,0,0,1,0],
     [0,0,0,0,1]]
b_ = [[2,3,1,0,5],
     [0,1,0,3,2],
     [0,0,2,2,1],
     [0,3,0,1,0],
     [23,0,2,1,0]]
c_ = [[3,3,1,2,0],
     [1,0,0,3,2],
     [2,0,2,2,1],
     [5,3,0,3,0],
     [2,0,2,1,1]]

In [26]:
# Ahhoz, hogy egy mátrixot tudjunk numpyban kezelni, a matrix() függvénybe kell beadni az listába ágyazott listát

a = np.matrix(a_)
print(a)
print(type(a))
print(a.dtype)
a

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
<class 'numpy.matrix'>
int32


matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [27]:
# Ha egy típikus mátrixot szeretnénk létrehozni, akkor vannak alap mátrixok, amik legenerálhatók

# 4*4-es 0-kból álló mátrix
print(np.zeros((4,4), dtype="int32"))
# 4*4-es 1-ekből álló mátrix
print(np.ones((4,4), dtype="int32"))
# 4*4-es véletlen számokat generáló mátrix (minx: 0, max:1)
print(np.random.rand(4,4))
# Egységmátrix (Erről minimálisan lesz szó később, mátrixelmélettel érdemes foglalkozni, ha valakit éredekel a téma)
print(np.diag([1,1,1,1]))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0.82945424 0.03803899 0.98464293 0.61913286]
 [0.88327565 0.22798311 0.66463134 0.60119517]
 [0.50383579 0.75831197 0.69566288 0.93346712]
 [0.52716531 0.19682105 0.67115916 0.104339  ]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


___
## Mátrixműveletek
Valójában a tényleges értéke an umpynak most következik.\n
Olyan műveleteket tudunk végezni numpy mátrixokon, amit sima tömbökkel nem tudnánk

In [54]:
# VIGYÁZZUNK
# Ha egy mátrixot átadunk egy másik változónak, az nem az értékeket adja át
# Ilyenkor annyit csinálunk, hogy a és b változó is ugyanarra a mátrixra mutat
# Így, ha egyiket változtatjuk, akkor A MÁSIK IS VÁLTOZIK
a = np.matrix(a_)
print(a)
b = a
b[0,0] = 10
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[10  0  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0  1]]


In [56]:
# Ezt a copy függvénnyel tudjuk megoldani. Ilyenkor csinálunk egy másolatot a mátrixról, és az új változó a másolatra fog mutatni.
a = np.matrix(a_)
print(a)
b = a.copy()
b[0,0] = 10
print(a)
print(b)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[10  0  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0  1]]


In [28]:
# Összeadás
a = np.matrix(a_)
b = np.matrix(b_)

print(a)
print(b)
print(a+b)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]
[[ 3  3  1  0  5]
 [ 0  2  0  3  2]
 [ 0  0  3  2  1]
 [ 0  3  0  2  0]
 [23  0  2  1  1]]


In [29]:
# Kivonás
a = np.matrix(a_)
b = np.matrix(b_)

print(b)
print(a)
print(b-a)

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[ 1  3  1  0  5]
 [ 0  0  0  3  2]
 [ 0  0  1  2  1]
 [ 0  3  0  0  0]
 [23  0  2  1 -1]]


In [30]:
# Szorzás, itt a matematikából ismert mátrix szorzásról van szó, matematikában érdemes utánanézni
c = np.matrix(c_)
b = np.matrix(b_)

print(c)
print(b)
print(c+b)

[[3 3 1 2 0]
 [1 0 0 3 2]
 [2 0 2 2 1]
 [5 3 0 3 0]
 [2 0 2 1 1]]
[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]
[[ 5  6  2  2  5]
 [ 1  1  0  6  4]
 [ 2  0  4  4  2]
 [ 5  6  0  4  0]
 [25  0  4  2  1]]


In [31]:
# Minden érték növelése egy számmal
a = np.matrix(a_)
print(a)
print(a+1)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[2 1 1 1 1]
 [1 2 1 1 1]
 [1 1 2 1 1]
 [1 1 1 2 1]
 [1 1 1 1 2]]


In [32]:
# Minden érték szorzása egy számmal
a = np.matrix(a_)
print(a)
print(2*a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]


___
## Indexelés

In [33]:
# Vegyük ezt a mátrixot
b = np.matrix(b_)
b

matrix([[ 2,  3,  1,  0,  5],
        [ 0,  1,  0,  3,  2],
        [ 0,  0,  2,  2,  1],
        [ 0,  3,  0,  1,  0],
        [23,  0,  2,  1,  0]])

In [51]:
# Ahogy a kiírt struktúra is mutatja, ha simán egy indexet használunk, akkor a sort kapjuk vissza
print(b)
b[0]

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]


matrix([[23,  0,  2,  1,  0]])

In [52]:
# Itt is működik a negatív indexelés
print(b)
b[-2]

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]


matrix([[0, 3, 0, 1, 0]])

In [45]:
# Ezt követően arra gondolnánk, hogy tovább tudjuk indexelni
# Viszont ha jobban megnézzük, látszik, hogy egy mátrix a visszatérési értékünk
# Tehát a megszokott indexelés, amit listáknál használnánk nem fog működni, mert egy 1 soros mátrixnak az első sorát kapjuk vissza
print(b)
print(b[0][0])

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]
[[2 3 1 0 5]]


In [43]:
# Ehelyett ,-vel elválasztva kell beírni az indexeket
print(b)
b[0,0]

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]


2

In [46]:
# Ha egy intervallumot szeretnénk kiemelni, azt a :-tal tudjuk megtenni
# Az első index itt is a sorokra vonatkozik
print(b)
b[1:3]



[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]


matrix([[0, 1, 0, 3, 2],
        [0, 0, 2, 2, 1]])

In [47]:
# A listákhoz hasonlóan mödik a tól-ig egyik érték üresen hagyása
print(b)
b[:3]

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]


matrix([[2, 3, 1, 0, 5],
        [0, 1, 0, 3, 2],
        [0, 0, 2, 2, 1]])

In [48]:
# Ha a soron belül szeretnénk tól-ig intervallumot meghatározni, azt a vessző után a megszokott módon tudjuk megtenni
print(b)
b[1,1:3]

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]


matrix([[1, 0]])

In [50]:
# Ha egy 3*3-as részmátrixra van szükségünk, akkor azt egyszerűen mindkét érték intervallumként megadásával tudjuk megadni
print(b)
b[1:4, 1:4]

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]


matrix([[1, 0, 3],
        [0, 2, 2],
        [3, 0, 1]])

In [53]:
# És itt jön be az oszlop visszakapása
# Ha az első értékre csak :-ot írunk, az azt jelenti, hogy az összes értéket kérjük
# Tehát a következő megoldás azt jelenti, hogy az összes sor 3. elemét kérjük le
# Kicsit furcsán néz ki, de higgyétek el, ezt szeretnénk, és a következő pontban mutatom is, miért
print(b)
b[:,3]

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]


matrix([[0],
        [3],
        [2],
        [1],
        [1]])

## Oszlopműveletek
Mire is jó ez a rengeteg eddigi szenvedés?<br />
Oszlopot, sort is kényelmesen tudunk változtatni, amit 2D listával nem tudunk megtenni<br /> 
Nézzük is ez mit jelent<br /> 
<br /> 
Ha megnézzük az előző pontban a visszatérési értékek mindig mátrixok voltak<br /> 
Ez annyit tesz, hogy minden művelet végezhető a részmátrixra is, ami a teljesre működött

In [61]:
# Nézzük is, hogyan tudunk egy sort szorozni kettővel
b = np.matrix(b_)
print(b)
b[2]=2*b[2]
b

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]


matrix([[ 2,  3,  1,  0,  5],
        [ 0,  1,  0,  3,  2],
        [ 0,  0,  4,  4,  2],
        [ 0,  3,  0,  1,  0],
        [23,  0,  2,  1,  0]])

In [63]:
# Ha egy oszlopot le szeretnénk cserélni, egy másik oszloppal

b = np.matrix(b_)
print(b)
# Ehhez használok egy plussz változót, ami tárolja az egyik oszlopot, amíg a másikat másolom
tmp = b[:,2].copy()
b[:,2] = b[:,3]
b[:,3] = tmp
b

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]


matrix([[ 2,  3,  0,  1,  5],
        [ 0,  1,  3,  0,  2],
        [ 0,  0,  2,  2,  1],
        [ 0,  3,  1,  0,  0],
        [23,  0,  1,  2,  0]])

In [69]:
# Ha nem figyelnénk a copy-ra akkor a tmp egy olyan változó lenne, ami a 2. indexen lévő oszlopra mutatna
b = np.matrix(b_)
print(b)
# Tehát amikor ezzel egyenlővé tesszük a másik oszlopot, ugyanarra az adatra lesz rákötve két oszlop
tmp = b[:,2]
print(b)
# Amikor felülírjuk az első értéket minden jónak tűnik
b[:,2] = b[:,3]
print(b)
# Viszont a tmp-ből is az új b[:,2] értékeket fogjuk tudni kiolvasni
b[:,3] = tmp
print(b)

[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]
[[ 2  3  1  0  5]
 [ 0  1  0  3  2]
 [ 0  0  2  2  1]
 [ 0  3  0  1  0]
 [23  0  2  1  0]]
[[ 2  3  0  0  5]
 [ 0  1  3  3  2]
 [ 0  0  2  2  1]
 [ 0  3  1  1  0]
 [23  0  1  1  0]]
[[ 2  3  0  0  5]
 [ 0  1  3  3  2]
 [ 0  0  2  2  1]
 [ 0  3  1  1  0]
 [23  0  1  1  0]]


matrix([[ 2,  3, -1,  0,  5],
        [ 0,  1,  3,  3,  2],
        [ 0,  0,  2,  2,  1],
        [ 0,  3,  1,  1,  0],
        [23,  0,  1,  1,  0]])